QMeter: QMeter Class Reference
QMeter Class Reference
QMeter is a custom widget plugin to display values. It consists of a scale and a needle to show the value within a lower and an upper limit. The angle associated to the limits in the widget scale can be modified by appropriate slots. A threshold limit can be enabled to handle alarm signals coherent with the input value. Once installed in Qt designer, right click on the widget and select HelpQMeter..., the associated help dialog will be displayed to show more details about the widget.
#include <qmeter.h>
Public Types
enum ErrorCode {
MaxValueError = 1, MinValueError, ThresholdError, TargetError,
PrecisionError, ColorError, UnitsEmpty, OutOfRange
}
ErrorCode : This enum represent the code returned by the error signal.
Public Slots
void setValue (double)
void setValue (int)
void setMinValue (double)
void setMinValue (int)
void setMaxValue (double)
void setMaxValue (int)
void setThreshold (double)
void setThreshold (int)
void setPrecision (int)
void setUnits (QString)
void setSteps (int)
void setStartAngle (double)
void setEndAngle (double)
void setForeground (QColor)
void setBackground (QColor)
void setThresholdEnabled (bool)
void setNumericIndicatorEnabled (bool)
Signals
void errorSignal (int)
void thresholdAlarm (bool)
Public Member Functions
QMeter (QWidget *parent=0)
Constructor.
double value () const
double minValue () const
double maxValue () const
double threshold () const
int precision () const
QString units () const
int steps () const
double startAngle () const
double endAngle () const
QColor foreground () const
QColor background () const
bool enableThreshold () const
bool enableNumericIndicator () const
Protected Member Functions
void thresholdManager ()
void paintEvent (QPaintEvent *event)
void drawCrown (QPainter *painter)
void drawBackground (QPainter *painter)
void drawTicks (QPainter *painter)
void drawScale (QPainter *painter)
void drawUnits (QPainter *painter)
void drawIndicator (QPainter *painter)
void drawThresholdLine (QPainter *painter)
void drawNumericValue (QPainter *painter)
Protected Attributes
double m_value
double m_maxValue
double m_minValue
int m_precision
QString m_units
int m_steps
double m_startAngle
double m_endAngle
double m_threshold
bool m_thresholdFlag
bool m_thresholdEnabled
bool m_numericIndicatorEnabled
QColor m_foreground
QColor m_background
Properties
double value
double minValue
double maxValue
double threshold
int precision
QString units
int steps
double startAngle
double endAngle
QColor foreground
QColor background
bool enableThreshold
bool enableNumericIndicator
Detailed Description
QMeter is a custom widget plugin to display values. It consists of a scale and a needle to show the value within a lower and an upper limit. The angle associated to the limits in the widget scale can be modified by appropriate slots. A threshold limit can be enabled to handle alarm signals coherent with the input value. Once installed in Qt designer, right click on the widget and select HelpQMeter..., the associated help dialog will be displayed to show more details about the widget.
Definition at line 44 of file qmeter.h.
Member Enumeration Documentation
enum QMeter::ErrorCode
ErrorCode : This enum represent the code returned by the error signal.
Enumerator:
MaxValueError
MinValueError
ThresholdError
TargetError
PrecisionError
ColorError
UnitsEmpty
OutOfRange
Definition at line 66 of file qmeter.h.
Constructor & Destructor Documentation
QMeter::QMeter (QWidget * parent = 0)
Constructor.
Parameters:
parent Parent Widget
Definition at line 64 of file qmeter.cpp.
References m_background, m_foreground, m_precision, m_steps, and m_thresholdFlag.
Member Function Documentation
double QMeter::value () const [inline]
Returns:
The current displayed value
Definition at line 76 of file qmeter.h.
double QMeter::minValue () const [inline]
Returns:
The minimum widget scale value
Definition at line 81 of file qmeter.h.
double QMeter::maxValue () const [inline]
Returns:
The maximum widget scale value
Definition at line 86 of file qmeter.h.
double QMeter::threshold () const [inline]
Returns:
The threshold
Definition at line 91 of file qmeter.h.
int QMeter::precision () const [inline]
Returns:
The number of decimals displayed in the widget scale
Definition at line 96 of file qmeter.h.
QString QMeter::units () const [inline]
Returns:
The measurement unit string
Definition at line 101 of file qmeter.h.
int QMeter::steps () const [inline]
Returns:
The number of steps in the widget scale
Definition at line 106 of file qmeter.h.
double QMeter::startAngle () const [inline]
Returns:
The starting angle associated to the minimum value for the widget scale
Definition at line 111 of file qmeter.h.
double QMeter::endAngle () const [inline]
Returns:
The end angle associated to the minimum value for the widget scale
Definition at line 116 of file qmeter.h.
QColor QMeter::foreground () const [inline]
Returns:
The foreground color used for the widget
Definition at line 121 of file qmeter.h.
QColor QMeter::background () const [inline]
Returns:
The background color used for the widget
Definition at line 126 of file qmeter.h.
bool QMeter::enableThreshold () const [inline]
Returns:
The enableThreshold flag
Definition at line 131 of file qmeter.h.
bool QMeter::enableNumericIndicator () const [inline]
Returns:
The enableNumericIndicator flag
Definition at line 136 of file qmeter.h.
void QMeter::errorSignal (int) [signal]
This signal is emitted to report an error condition.
Referenced by setMaxValue(), setThreshold(), and setValue().
void QMeter::thresholdAlarm (bool) [signal]
This signal reports a value true when the input value exceeds for the first time the threshould limit and reports a value false when the input value decreases under the threshold limit. That means errorSignal is emitted only one time (with true argument) when the input passes from a value < threshold to a value > threshold and only one time (with false argument) when the input decreases under the threshold limit.
Referenced by thresholdManager().
void QMeter::setValue (double value) [slot]
This slot is used to set QMeter value
Definition at line 76 of file qmeter.cpp.
References errorSignal(), m_maxValue, m_minValue, m_thresholdEnabled, m_value, OutOfRange, and thresholdManager().
Referenced by Ui_propertiesDialog::setupUi(), and setValue().
void QMeter::setValue (int value) [slot]
This is an overloaded member function, provided for convenience.
Definition at line 99 of file qmeter.cpp.
References setValue().
void QMeter::setMinValue (double value) [slot]
This slot is used to set the lower limit of the QMeter scale.
Definition at line 105 of file qmeter.cpp.
References m_minValue.
Referenced by setMinValue(), and Ui_propertiesDialog::setupUi().
void QMeter::setMinValue (int value) [slot]
This is an overloaded member function, provided for convenience.
Definition at line 111 of file qmeter.cpp.
References setMinValue().
void QMeter::setMaxValue (double value) [slot]
This slot is used to set the upper limit of the QMeter scale.
Definition at line 117 of file qmeter.cpp.
References errorSignal(), m_maxValue, m_minValue, and MaxValueError.
Referenced by setMaxValue(), and Ui_propertiesDialog::setupUi().
void QMeter::setMaxValue (int value) [slot]
This is an overloaded member function, provided for convenience.
Definition at line 129 of file qmeter.cpp.
References setMaxValue().
void QMeter::setThreshold (double value) [slot]
This slot is used to set the threshold limit. See thresholdAlarm for more info.
Definition at line 135 of file qmeter.cpp.
References errorSignal(), m_maxValue, m_minValue, m_threshold, and ThresholdError.
Referenced by setThreshold().
void QMeter::setThreshold (int value) [slot]
This is an overloaded member function, provided for convenience.
Definition at line 147 of file qmeter.cpp.
References setThreshold().
void QMeter::setPrecision (int precision) [slot]
This slot is used to set the number of decimal digits for the QMeter scale and QMeter numerical value.
Definition at line 154 of file qmeter.cpp.
References m_precision.
void QMeter::setUnits (QString units) [slot]
This slot is used to set the measurement units displyed in the QMeter widget.
Definition at line 161 of file qmeter.cpp.
References m_units.
Referenced by Ui_propertiesDialog::retranslateUi().
void QMeter::setSteps (int nSteps) [slot]
This slot is used to set the number of spets in the QMeter scale.
Definition at line 190 of file qmeter.cpp.
References m_steps.
void QMeter::setStartAngle (double value) [slot]
This represents the starting angle correspondign to the lower limit for the QMeter scale. Positive and negative angles can be used.
Definition at line 196 of file qmeter.cpp.
References m_startAngle.
Referenced by Ui_propertiesDialog::setupUi().
void QMeter::setEndAngle (double value) [slot]
This represents the end angle corresponding to the upper limit for the QMeter scale. Positive and negative angles can be used.
Definition at line 202 of file qmeter.cpp.
References m_endAngle.
Referenced by Ui_propertiesDialog::setupUi().
void QMeter::setForeground (QColor newForeColor) [slot]
This slot is used to set the widget foreground color.
Definition at line 210 of file qmeter.cpp.
References m_foreground.
void QMeter::setBackground (QColor newBackColor) [slot]
This slot is used to set the widget background color.
Definition at line 216 of file qmeter.cpp.
References m_background.
void QMeter::setThresholdEnabled (bool enable) [slot]
This slot allows to enable the threshold management. See thresholdAlarm for more info.
Definition at line 239 of file qmeter.cpp.
References m_thresholdEnabled.
Referenced by QMeterPropertiesDialog::QMeterPropertiesDialog().
void QMeter::setNumericIndicatorEnabled (bool enable) [slot]
Thi slot allows to enable the numerical value display
Definition at line 245 of file qmeter.cpp.
References m_numericIndicatorEnabled.
Referenced by QMeterPropertiesDialog::QMeterPropertiesDialog().
The documentation for this class was generated from the following files:
qmeter.h
qmeter.cpp
qmeterdrawfunctions.cpp